runtime: python39
entrypoint: gunicorn main:app
instance_class: F1

handlers:
- url: /static
  static_dir: static
- url: /.*
  secure: always
  script: auto

automatic_scaling:
  min_instances: 2
  max_instances: 22
  min_pending_latency: 8s
  max_pending_latency: 10s
  max_idle_instances: 7
  target_cpu_utilization: 0.75
  target_throughput_utilization: 0.75